# Site settings
title: Anton's
email: your-email@domain.com
description: "Starting to Jekyll."
baseurl: ""
url: "www.anton23.com"
twitter_username: antonmaximus
github_username:  antonmaximus

# Build settings
markdown: kramdown
permalink: pretty
